CREATE TABLE EVERYDAYGYM_WORKOUT(
    workout_num NUMBER PRIMARY KEY
    , workout_type VARCHAR2(200) NOT NULL
    , workout_kg NUMBER NOT NULL
    , workout_counts NUMBER NOT NULL
    , workout_setvolume NUMBER NOT NULL
    , user_id VARCHAR2(50) NOT NULL CONSTRAINT WORKOUT_FK REFERENCES EVERYDAYGYM_MEMBER(user_id) ON DELETE CASCADE
    , workout_indate DATE DEFAULT SYSDATE
);

CREATE SEQUENCE EVERYDAYGYM_WORKOUT_SEQ;