

CREATE TABLE EVERYDAYGYM_MEMBERSHIP(
    membership_num NUMBER PRIMARY KEY
    ,  membership_month NUMBER DEFAULT 0
    , user_id VARCHAR2(50) NOT NULL CONSTRAINT MEMBERSHIP_FK REFERENCES EVERYDAYGYM_MEMBER(user_id) ON DELETE CASCADE
    , membership_processed NUMBER DEFAULT 0
);

CREATE SEQUENCE EVERYDAYGYM_MEMBERSHIP_SEQ;
    